import Head from "next/head";
import Banner from "../components/banner/banner";
import SectionCards from "../components/card/section-cards";
import NavBar from "../components/nav/navbar";
import { getVideos } from "../lib/videos";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  const disneyVideos = await getVideos();
  return {
    props: {
      disneyVideos,
    },
  };
}

export default function Home({ disneyVideos }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netvideo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username={"username@go.com"} />

      <Banner
        title={"Clifford the red dog"}
        subtitle={"a very cute dog"}
        imgUrl={"/static/clifford.webp"}
      />

      <div className={styles.sectionWrapper}>
        <SectionCards title={"Disney"} videos={disneyVideos} size="large" />
        <SectionCards title={"Disney"} videos={disneyVideos} size="large" />
      </div>
    </div>
  );
}
